import Head from 'next/head'
import Header from '../components/Header'
import Services from '../components/Services'
import Working from '../components/Working'
import Camps from '../components/Camps'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Zeesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/* Header */}
      <Header />
      {/* Services */}
     
      <Services />
    

      {/* How it works */}
      <Working />
      <Camps />
      {/* footer */}

      <Footer />
    </div>
  )
}
